#!/usr/bin/env bun
/**
 * OpenAPI generation — machine-readable API surface, derived from the SAME
 * @effect/schema contracts the code uses (shared/src), so the spec cannot
 * drift from the types. `--check` mode diffs the committed openapi.json
 * against a fresh render and fails CI when stale (the `lint` job runs it).
 *
 * Adding a slice: register its path entry below using the slice's shared
 * schema; `bun run openapi:gen` rewrites openapi.json.
 */
import { join } from "node:path"
import { JSONSchema } from "@effect/schema"
import { ApiErrorBody, HealthStatus } from "../shared/src"

// JSONSchema.make emits a draft-07 `$schema` key; OpenAPI 3.1 schemas don't
// carry one per-component, so strip it.
const schemaOf = (schema: Parameters<typeof JSONSchema.make>[0]): Record<string, unknown> => {
  const { $schema: _, ...rest } = JSONSchema.make(schema) as Record<string, unknown>
  return rest
}

const errorResponse = {
  description: "Typed failure in the shared ApiErrorBody envelope.",
  content: { "application/json": { schema: schemaOf(ApiErrorBody) } },
}

const doc = {
  openapi: "3.1.0",
  info: {
    title: "ts-axioms service",
    version: "0.0.0",
    description:
      "Generated by scripts/generate-openapi.ts from the shared @effect/schema contracts. Do not edit by hand.",
  },
  paths: {
    "/health": {
      get: {
        summary: "Service health",
        parameters: [
          {
            name: "verbose",
            in: "query",
            required: false,
            schema: { type: "string", enum: ["true", "false", "1", "0"] },
            description: "Echo a `verbose: true` field on the payload.",
          },
        ],
        responses: {
          "200": {
            description: "Liveness, build version and uptime.",
            content: { "application/json": { schema: schemaOf(HealthStatus) } },
          },
          "400": errorResponse,
        },
      },
    },
  },
}

const target = join(import.meta.dir, "..", "openapi.json")
const rendered = `${JSON.stringify(doc, null, 2)}\n`

if (process.argv.includes("--check")) {
  const existing = (await Bun.file(target).exists()) ? await Bun.file(target).text() : ""
  if (existing !== rendered) {
    console.error("✖ openapi.json is stale — run `bun run openapi:gen` and commit the result.")
    process.exit(1)
  }
  console.error("✓ openapi.json is up to date")
} else {
  await Bun.write(target, rendered)
  console.error("wrote openapi.json")
}
